spring.application.name=paf
spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT:8080}

spring.data.mongodb.uri=mongodb+srv://root:root@cluster0.smdoxwn.mongodb.net/paf_smart_campus?authSource=admin&retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:830820435170-9jv4v8dqr0oalvjk4tfriueo72sutmja.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,profile,email

app.frontend.base-url=http://localhost:5173
app.mongodb.verify-on-startup=true