spring.application.name=paf
spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=false

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:830820435170-9jv4v8dqr0oalvjk4tfriueo72sutmja.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,profile,email

app.frontend.base-url=http://localhost:5173
app.mongodb.verify-on-startup=true

# Increase limits for profile picture uploads (Base64 JSON)
server.tomcat.max-http-form-post-size=10MB
spring.codec.max-in-memory-size=10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB